spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_data
    username: postgres
    password: bookmaker
    validationQuery: SELECT 1
    hikari:
	maximum-pool-size: 48
	leak-detection-threshold: 48

management:
  server:
    port: 8093
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
eureka:
  client:
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/
